# Generated by Django 5.0.6 on 2024-05-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0004_empresas_confirmacion_contraseña_empresas_contraseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresas',
            old_name='confirmacion_contraseña',
            new_name='confirmacion_contrasena',
        ),
        migrations.RenameField(
            model_name='empresas',
            old_name='contraseña',
            new_name='contrasena',
        ),
        migrations.RenameField(
            model_name='postulantes',
            old_name='confirmacion_contraseña',
            new_name='confirmacion_contrasena',
        ),
        migrations.RenameField(
            model_name='postulantes',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
