# Generated by Django 5.0.6 on 2024-06-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0005_rename_confirmacion_contraseña_empresas_confirmacion_contrasena_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresas', models.ManyToManyField(to='Sistema_autenticacion_registro.empresas')),
                ('postulantes', models.ManyToManyField(to='Sistema_autenticacion_registro.postulantes')),
            ],
        ),
    ]
