# Generated by Django 5.0.6 on 2024-06-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0007_delete_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoDocumentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abreviatura', models.CharField(max_length=255, verbose_name='Abreviatura')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripcion')),
            ],
        ),
    ]
