# Generated by Django 5.0.6 on 2024-06-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0008_tipodocumentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulantes',
            name='nacionalidad',
            field=models.CharField(default='Colombiano', max_length=255, verbose_name='Nacionalidad'),
        ),
    ]
