# Generated by Django 5.0.6 on 2024-06-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0009_postulantes_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulantes',
            name='nacionalidad',
            field=models.CharField(max_length=255, verbose_name='Nacionalidad'),
        ),
    ]
