# Generated by Django 5.0.6 on 2024-06-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0010_alter_postulantes_nacionalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='localidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('localidades', models.CharField(max_length=255, verbose_name='localidades')),
            ],
        ),
    ]
