# Generated by Django 5.0.6 on 2024-06-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0013_alter_sexo_sexo_alter_tipodiscapacidad_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulantes',
            old_name='descripcionDiscapacidad',
            new_name='descripcion_discapacidad',
        ),
    ]
