# Generated by Django 5.0.6 on 2024-06-06 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0016_postulantes_id_localidad_postulantes_id_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulantes',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_autenticacion_registro.localidad'),
        ),
        migrations.AlterField(
            model_name='postulantes',
            name='id_sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_autenticacion_registro.sexo'),
        ),
        migrations.AlterField(
            model_name='postulantes',
            name='id_tipo_discapacidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_autenticacion_registro.tipo_discapacidad'),
        ),
        migrations.AlterField(
            model_name='postulantes',
            name='id_tipo_documentos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_autenticacion_registro.tipo_documentos'),
        ),
    ]
