# Generated by Django 5.0.6 on 2024-06-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0017_alter_postulantes_id_localidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulantes',
            old_name='id_localidad',
            new_name='localidad',
        ),
        migrations.RenameField(
            model_name='postulantes',
            old_name='id_sexo',
            new_name='sexo',
        ),
        migrations.RenameField(
            model_name='postulantes',
            old_name='id_tipo_discapacidad',
            new_name='tipo_discapacidad',
        ),
        migrations.RenameField(
            model_name='postulantes',
            old_name='id_tipo_documentos',
            new_name='tipo_documentos',
        ),
    ]
