# Generated by Django 5.0.6 on 2024-06-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0018_rename_id_localidad_postulantes_localidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulantes',
            name='cedula',
            field=models.CharField(max_length=255, unique=True, verbose_name='Número de Cédula'),
        ),
    ]
