# Generated by Django 5.0.6 on 2024-06-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0019_alter_postulantes_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='confirmacion_contrasena',
            field=models.CharField(max_length=255, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='contrasena',
            field=models.CharField(max_length=255, verbose_name='Contraseña'),
        ),
    ]
