# Generated by Django 5.0.6 on 2024-06-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0020_alter_empresas_confirmacion_contrasena_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado_civil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_civil', models.CharField(max_length=255, verbose_name='estado_civil')),
            ],
        ),
        migrations.AlterField(
            model_name='empresas',
            name='confirmacion_contrasena',
            field=models.CharField(max_length=255, verbose_name='Confirmación de contraseña'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='correo',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nit',
            field=models.CharField(max_length=255, unique=True, verbose_name='Número de NIT'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='rut',
            field=models.CharField(max_length=255, unique=True, verbose_name='Número de RUT'),
        ),
    ]
