# Generated by Django 5.0.6 on 2024-06-07 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0021_estado_civil_alter_empresas_confirmacion_contrasena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulantes',
            name='estado_civil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sistema_autenticacion_registro.estado_civil'),
        ),
    ]
