# Generated by Django 5.0.6 on 2024-06-07 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0022_postulantes_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulantes',
            name='estado_civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_autenticacion_registro.estado_civil'),
        ),
    ]
