# Generated by Django 5.0.6 on 2024-06-07 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0023_alter_postulantes_estado_civil'),
    ]

    operations = [
        migrations.CreateModel(
            name='grupo_sanguineo_rh',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grupo_sanguineo_rh', models.CharField(max_length=255, verbose_name='grupo_sanguineo_rh')),
            ],
        ),
        migrations.AddField(
            model_name='postulantes',
            name='grupo_sanguineo_rh',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sistema_autenticacion_registro.grupo_sanguineo_rh'),
        ),
    ]
