# Generated by Django 5.0.6 on 2024-06-07 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0024_grupo_sanguineo_rh_postulantes_grupo_sanguineo_rh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulantes',
            name='grupo_sanguineo_rh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_autenticacion_registro.grupo_sanguineo_rh'),
        ),
    ]
