# Generated by Django 5.0.6 on 2024-06-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0026_nivel_idioma_postulantes_idioma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulantes',
            name='idioma',
            field=models.CharField(max_length=255, verbose_name='Idioma'),
        ),
    ]
