# Generated by Django 5.0.6 on 2024-06-07 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_autenticacion_registro', '0027_alter_postulantes_idioma'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulantes',
            name='nivel_idioma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sistema_autenticacion_registro.nivel_idioma'),
        ),
    ]
